name: "Tamouse's Recipe File"
markdown: redcarpet
redcarpet:
  extensions:
    - lax_spacing
# pygments: true

source: source
destination: public
deployment:
  directory: gh-pages
  branch: gh-pages
  remote: origin

exclude: [README.md]
baseurl: /recipe-blog
